### ISSUE TITLE
FIA money quantity appears "scalar NaN"

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#82]
After saving and loading the game the "FIA Money" tab in the HUD appeared "scalar NaN" instead of the amount of money that I had.

**P.S. Tested with ACE with FIX branch in MP**

START POSSIBLE LOG SECTION

if (_type == "Survivor") exitWith {
["", "",>
21:32:48   Error position: <_type == "Survivor") exitWith {
["", "",>
21:32:48   Error Undefined variable in expression: _type
21:32:48 File arsenal\fnc_getBestEquipment.sqf [AS_fnc_getBestEquipment], line 7
21:32:50 soldier[I_Soldier_AR_F]:Some of magazines weren't stored in soldier Vest or Uniform?
21:32:51 soldier[I_Soldier_AT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
21:32:51 soldier[I_Soldier_AT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
21:32:51 "[AS] Error: O Alpha 3-1:2 was initialized without side"
21:32:51 "[AS] Error: O Alpha 3-1:1 was initialized with invalid side 'UNKNOWN'"
21:32:51 "[AS] Error: O Alpha 3-1:3 was initialized without side"
21:32:51 "[AS] Error: O Alpha 3-1:1 was initialized with invalid side 'UNKNOWN'"
21:32:51 "[AS] Error: O Alpha 3-1:4 was initialized without side"
21:32:51 "[AS] Error: O Alpha 3-1:1 was initialized with invalid side 'UNKNOWN'"
21:32:51 "[AS] Error: O Alpha 3-1:5 was initialized without side"
21:32:51 "[AS] Error: O Alpha 3-1:1 was initialized with invalid side 'UNKNOWN'"
21:32:51 "[AS] Error: O Alpha 3-1:6 was initialized without side"
21:32:51 "[AS] Error: O Alpha 3-1:1 was initialized with invalid side 'UNKNOWN'"
21:32:51 "[AS] Error: O Alpha 3-1:7 was initialized without side"
21:32:51 "[AS] Error: O Alpha 3-1:1 was initialized with invalid side 'UNKNOWN'"
21:32:51 "[AS] Error: O Alpha 3-1:8 was initialized without side"
21:32:51 "[AS] Error: O Alpha 3-1:1 was initialized with invalid side 'UNKNOWN'"
21:32:51 "[AS] Error: O Alpha 3-1:9 was initialized without side"
21:32:51 "[AS] Error: O Alpha 3-1:1 was initialized with invalid side 'UNKNOWN'"
21:32:57 Error in expression <_persistent setVariable ["resourcesFIA",_FIAnewMoney,true]);
(AS_persistent setV>
21:32:57   Error position: <_FIAnewMoney,true]);
(AS_persistent setV>
21:32:57   Error Undefined variable in expression: _fianewmoney
21:32:57 File fnc_updateAll.sqf [AS_fnc_updateAll], line 142
21:33:00 "DICT:get([1675861: empty.p3d,""cars_transport"",""cost""]):ERROR: invalid key"
21:33:00 "DICT:get([1675861: empty.p3d,""cars_transport"",""count""]):ERROR: invalid key"
21:33:00 Error in expression <Farsenal_fnc_get)} forEach _categories;
_all

END POSSIBLE LOG SECTION

**Comment by LordGolias** [comment]
Fixed in 6b3c1572abbcb165b462585486808ca09613330f

**Comment by Warhammer47** [comment]
This still persists in the DEVELOP branch. I think it might be related to having more then 10K in the FIA account

**Comment by LordGolias** [comment]
It is because some vehicle types still have not its cost defined. Once this happens once and the money is saved, it will persist forever. Could you send me the log?

**Comment by Warhammer47** [comment]
Ok, here is the log, I think it's around time 2:14:39:

[Arma3_x64_2017-10-25_22-06-03.txt](https://github.com/LordGolias/antistasi/files/1417856/Arma3_x64_2017-10-25_22-06-03.txt)
